ARG BUNNYLAND_SERVER_IMAGE=ghcr.io/thalismind/bunnyland-server:main
FROM ${BUNNYLAND_SERVER_IMAGE}

COPY server /tmp/bunnyland-studio/server
RUN /app/.venv/bin/pip install --no-cache-dir /tmp/bunnyland-studio/server \
    && rm -r /tmp/bunnyland-studio
