import { expect, test, type Route } from '@playwright/test';

const claim = {
  claim_id: '0123456789abcdef0123456789abcdef',
  character_id: '101',
  owner_subject: 'owner-a',
  claimed_at_epoch: 2,
  last_activity_epoch: 20,
  autonomous_controller_active: true,
};

const projection = {
  world_epoch: 20,
  character_id: '101',
  character_name: 'Mira',
  claim,
  van: {
    name: 'Kitsune',
    description: 'cream camper van',
    fuel_liters: 18,
    tank_liters: 60,
    estimated_range_km: 162,
    reliability: 'fair',
    broken_down: true,
    current_location_id: 'copper',
    autonomous_controller_active: true,
  },
  scene: {
    room_id: '202',
    room_name: 'Copper Hollow Repair Yard',
    visible_characters: ['Inez the mechanic'],
  },
  influences: [],
  media_available: { image: true, video: true },
};

const journey = {
  mode: 'fictional',
  attribution: 'Fictional geography generated by Bunnyland Studio',
  tile_url: '',
  current_location_id: 'copper',
  warnings: ['Fuel is low before the next long leg.'],
  locations: [
    {
      id: 'rose',
      name: 'Rose Junction',
      kind: 'town',
      point: { latitude: 35, longitude: -105 },
    },
    {
      id: 'copper',
      name: 'Copper Hollow',
      kind: 'repair',
      point: { latitude: 35.5, longitude: -104.5 },
    },
    {
      id: 'camp',
      name: 'Moon Camp',
      kind: 'camp',
      point: { latitude: 35.3, longitude: -104.1 },
    },
  ],
  segments: [
    {
      id: 'actual',
      from_location_id: 'rose',
      to_location_id: 'copper',
      state: 'completed',
      distance_km: 100,
      occurred_at_epoch: 16,
    },
    {
      id: 'detour',
      from_location_id: 'copper',
      to_location_id: 'camp',
      state: 'detour',
      distance_km: 24,
      occurred_at_epoch: 18,
    },
  ],
};

const journal = [
  {
    id: 'breakdown',
    kind: 'breakdown',
    summary: 'The cooling system lost pressure. Inez recommends a broad pressure test.',
    location_id: 'copper',
    occurred_at_epoch: 20,
    first_person: false,
    pinned: false,
    media_job_id: '',
    media_kind: '',
    media_source_event_id: '',
    media_status: '',
    media_url: '',
    media_error: '',
  },
];

const memories = [
  {
    id: 'memory-1',
    text: 'Inez heard the belt squeal before the steam appeared.',
    tags: ['mechanic', 'studio'],
    source: 'bunnyland.studio',
    created_at_epoch: 19,
  },
];

const fulfill = (route: Route, body: unknown, status = 200) =>
  route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) });

test('claim, detour, breakdown, mechanic, reflection, and media stay influence-scoped', async ({
  page,
}) => {
  let claimed = false;
  let mediaRequested = false;
  let journalReadsAfterMedia = 0;
  let journalMoments = journal;
  const requestedPaths: string[] = [];
  const mediaBodies: unknown[] = [];
  await page.route('**/api/v1/**', route => {
    const request = route.request();
    const path = new URL(request.url()).pathname;
    requestedPaths.push(path);
    if (path.endsWith('/auth/session')) {
      if (request.method() === 'GET') {
        return fulfill(route, { detail: 'authentication required' }, 401);
      }
      return fulfill(route, {
        subject: 'owner-a',
        scopes: ['world:play'],
        expires_at: 9999999999,
        rotate_after: null,
        rotation_eligible: false,
      });
    }
    if (path.endsWith('/projection')) {
      return claimed
        ? fulfill(route, projection)
        : fulfill(route, { detail: 'claim required' }, 403);
    }
    if (path.endsWith('/characters')) {
      return fulfill(route, [{ id: '101', name: 'Mira', claimed: false }]);
    }
    if (path.endsWith('/claims') && request.method() === 'POST') {
      claimed = true;
      return fulfill(route, claim, 201);
    }
    if (path.endsWith('/map')) return fulfill(route, journey);
    if (path.endsWith('/routes')) {
      return fulfill(route, [
        {
          id: 'route',
          title: 'Westward',
          adherence: 'balanced',
          status: 'active',
          current_waypoint: 1,
          waypoints: ['rose', 'copper', 'camp'],
        },
      ]);
    }
    if (path.endsWith('/memories') && request.method() === 'GET') {
      return fulfill(route, memories);
    }
    if (path.endsWith('/journal')) {
      if (!mediaRequested) return fulfill(route, journalMoments);
      journalReadsAfterMedia += 1;
      const completed = journalReadsAfterMedia > 1;
      journalMoments = [
        {
          ...journalMoments[0],
          media_job_id: 'image-job',
          media_kind: 'image',
          media_source_event_id: 'breakdown',
          media_status: completed ? 'succeeded' : 'queued',
          media_url: completed
            ? 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs='
            : '',
        },
      ];
      return fulfill(route, journalMoments);
    }
    if (path.endsWith('/influences') && request.method() === 'POST') {
      return fulfill(
        route,
        {
          id: 'influence',
          category: 'suggestion',
          strength: 'soft',
          pressure: 'balanced',
          text: 'Ask Inez what she noticed',
          need: '',
          need_delta: 0,
        },
        201,
      );
    }
    if (path.includes('/media')) {
      mediaRequested = true;
      mediaBodies.push(request.postDataJSON() as unknown);
      return fulfill(
        route,
        {
          id: 'image-job',
          kind: 'image',
          status: 'queued',
          source_event_id: 'breakdown',
          url: '',
          error: null,
        },
        202,
      );
    }
    if (path.includes('/pin')) {
      journalMoments = [{ ...journalMoments[0], pinned: request.method() === 'PUT' }];
      return fulfill(route, journalMoments[0]);
    }
    return fulfill(route, { id: 'saved' }, 201);
  });

  await page.goto('./');
  await page.getByLabel('Username').fill('owner-a');
  await page.getByLabel('Password').fill('correct horse battery staple');
  await page.getByRole('button', { name: 'Enter Studio' }).click();
  await expect(page.getByRole('heading', { name: 'Claim main character' })).toBeVisible();
  await page.getByLabel('Main character').selectOption('101');
  await page.getByRole('button', { name: 'Claim main character' }).click();

  await expect(page.getByText('Autonomous controller active')).toBeVisible();
  await expect(page.getByText('Copper Hollow Repair Yard')).toBeVisible();
  await expect(page.getByText('Inez the mechanic', { exact: false })).toBeVisible();
  await expect(page.getByText('Roadside assistance needed')).toBeVisible();
  await expect(page.locator('.route-completed')).toHaveCount(1);
  await expect(page.locator('.route-detour')).toHaveCount(1);
  await expect(page.getByText('The cooling system lost pressure', { exact: false })).toBeVisible();
  await expect(page.getByText('18.0 L · about 162 km · fair condition')).toBeVisible();
  await expect(page.getByText('World epoch 20')).toBeVisible();
  await expect(page.getByLabel('Itinerary name')).toHaveValue('Next chapter');
  await expect(page.getByText('rose (Rose Junction)', { exact: false })).toBeVisible();

  await page.getByRole('button', { name: 'Memory', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Existing memories' })).toBeVisible();
  await expect(page.getByText('Inez heard the belt squeal', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Influence', exact: true }).click();

  await page.getByRole('button', { name: 'Pin', exact: true }).click();
  await expect(page.getByText('★ Pinned')).toBeVisible();
  await page.getByRole('button', { name: 'Unpin', exact: true }).click();
  await expect(page.getByText('★ Pinned')).toHaveCount(0);

  await page.locator('.composer textarea').fill('Ask Inez what she noticed');
  await page.getByRole('button', { name: 'Save influence' }).click();
  await page
    .getByPlaceholder('Add a first-person travel reflection')
    .fill('I learned to listen before turning the key.');
  await page.getByRole('button', { name: 'Write reflection' }).click();
  await page.getByRole('button', { name: 'Generate image' }).click();

  await expect(page.getByText('Generating image…')).toBeVisible();
  await expect(page.getByRole('img', { name: 'Generated scene for:', exact: false })).toBeVisible();

  expect(requestedPaths.some(path => path.includes('/commands'))).toBe(false);
  expect(requestedPaths.some(path => path.includes('/queued-actions'))).toBe(false);
  expect(mediaBodies).toEqual([{ kind: 'image', event_id: '' }]);
});
