from __future__ import annotations

from dataclasses import replace
from typing import Literal

import pytest
from bunnyland.claims import ensure_character_control_claim_allowed
from bunnyland.core import (
    CharacterComponent,
    CommandCost,
    ControlledBy,
    HandlerContext,
    IdentityComponent,
    Lane,
    LLMControllerComponent,
    OnInsufficientPoints,
    RoomComponent,
    SubmittedCommand,
    WorldActor,
    execute_mutation_plan,
    replace_component,
    spawn_entity,
)
from bunnyland.foundation.history.mechanics import WorldHistoryRecordComponent
from bunnyland.foundation.needs.mechanics import HungerComponent
from bunnyland.foundation.persona.mechanics import GoalComponent
from bunnyland.imagegen.components import EventImageComponent, EventVideoComponent
from bunnyland.memory import InMemoryStore
from bunnyland.plugins import AddonMediaCapability, AddonMediaJob, PluginRegistry
from bunnyland.server.app import create_app
from bunnyland.server.auth import WORLD_ADMIN_SCOPE, WORLD_PLAY_SCOPE, TokenStore
from fastapi.testclient import TestClient

from bunnyland_studio.actions import DriveHandler, ReflectionHandler, RefuelHandler
from bunnyland_studio.api import _journal_resources, _normalized_media_status, _sync_journal_media
from bunnyland_studio.components import (
    GeoPoint,
    StudioBreakdownComponent,
    StudioGeographyComponent,
    StudioInfluenceClaimComponent,
    StudioInfluenceComponent,
    StudioJournalMomentComponent,
    StudioLocationComponent,
    StudioOwns,
    StudioRoadComponent,
    StudioRouteComponent,
    StudioTravelSegmentComponent,
    StudioVanComponent,
)
from bunnyland_studio.generators import (
    FICTIONAL_GENERATOR_NAME,
    REAL_GENERATOR_NAME,
    OpenMapClient,
    RouteEstimate,
    fictional_plan,
    real_generator,
)
from bunnyland_studio.mechanics import (
    BREAKDOWN_COOLDOWN_LEGS,
    CLAIM_REJECTION,
    add_influence,
    add_memory,
    claim_character,
    controller_snapshot,
    create_route,
    drive_van,
    explain_breakdown,
    influence_fragments,
    record_journal,
    recover_van,
    release_claim,
    remove_influence,
    reset_claim,
    route_fragments,
    van_fragments,
)
from bunnyland_studio.models import (
    FictionalGeneratorConfig,
    InfluenceRequest,
    LocationSelection,
    OverpassCenter,
    OverpassPoi,
    RealGeneratorConfig,
    RouteRequest,
    RouteWaypointRequest,
    StudioBlueprint,
)
from bunnyland_studio.plugin import PLUGIN_ID, plugin


def _blueprint() -> StudioBlueprint:
    return StudioBlueprint(
        character_name="Mira",
        appearance="short black hair and a red road jacket",
        persona="curious, practical, and kind",
        travel_motivation="find overlooked roadside stories",
        van_name="Kitsune",
        van_description="a compact cream camper van with a red stripe",
    )


def _studio_world() -> tuple[WorldActor, object, object, object]:
    actor = WorldActor()
    actor.plugins = PluginRegistry([plugin()])
    actor.memory_store = InMemoryStore()
    spawn_entity(
        actor.world,
        [
            RoomComponent(title="Rose Junction"),
            StudioLocationComponent(
                location_id="rose",
                name="Rose Junction",
                kind="town",
                point=GeoPoint(latitude=35, longitude=-105),
            ),
        ],
    )
    destination = spawn_entity(
        actor.world,
        [
            RoomComponent(title="Copper Hollow"),
            StudioLocationComponent(
                location_id="copper",
                name="Copper Hollow",
                kind="town",
                point=GeoPoint(latitude=35.5, longitude=-104.5),
            ),
        ],
    )
    character = spawn_entity(
        actor.world,
        [CharacterComponent(), IdentityComponent(name="Mira", kind="character")],
    )
    controller = spawn_entity(
        actor.world,
        [LLMControllerComponent(profile_name="studio", model="local", provider="ollama")],
    )
    actor.assign_controller(character.id, controller.id)
    van = spawn_entity(
        actor.world,
        [
            StudioVanComponent(
                name="Kitsune",
                description="cream camper van",
                current_location_id="rose",
                fuel_liters=40,
                tank_liters=60,
                km_per_liter=10,
            )
        ],
    )
    character.add_relationship(StudioOwns(kind="van"), van.id)
    geography = spawn_entity(
        actor.world,
        [
            StudioGeographyComponent(
                mode="fictional",
                title="Roseglass Highways",
                attribution="Fictional geography generated by Bunnyland Studio",
            )
        ],
    )
    character.add_relationship(StudioOwns(kind="geography"), geography.id)
    spawn_entity(
        actor.world,
        [
            StudioRoadComponent(
                road_id="rose-copper",
                from_location_id="rose",
                to_location_id="copper",
                distance_km=100,
                travel_minutes=90,
            )
        ],
    )
    return actor, character, controller, destination


def _command(character, controller, command_type: str, payload: dict[str, object]):
    edge = character.get_relationships(ControlledBy)[0][0]
    return SubmittedCommand(
        command_id=f"test-{command_type}",
        character_id=str(character.id),
        controller_id=str(controller.id),
        controller_generation=edge.generation,
        command_type=command_type,
        payload=payload,
        cost=CommandCost(),
        lane=Lane.WORLD,
        on_insufficient_points=OnInsufficientPoints.DENY,
        submitted_at_epoch=0,
    )


def _owned(actor: WorldActor, character, kind: str):
    return [
        actor.world.get_entity(target)
        for edge, target in character.get_relationships(StudioOwns)
        if edge.kind == kind and actor.world.has_entity(target)
    ]


def test_plugin_exports_typed_contracts_and_no_studio_command_route():
    contribution = plugin()

    assert contribution.id == PLUGIN_ID == "bunnyland.studio"
    assert [item.name for item in contribution.content.world_generators] == [
        REAL_GENERATOR_NAME,
        FICTIONAL_GENERATOR_NAME,
    ]
    assert {item.command_type for item in contribution.commands.action_definitions} == {
        "studio-van-drive",
        "studio-van-refuel",
        "studio-van-call-roadside-assistance",
        "studio-van-write-travel-reflection",
    }
    assert len(contribution.policy.character_control_claim_guards) == 1


def test_claim_resume_release_and_admin_reset_preserve_controller():
    actor, character, controller, _destination = _studio_world()
    before = controller_snapshot(character)

    claimed = claim_character(actor, str(character.id), "owner-a")
    resumed = claim_character(actor, str(character.id), "owner-a")

    assert resumed.claim_id == claimed.claim_id
    assert controller_snapshot(character) == before
    assert character.get_relationships(ControlledBy)[0][1] == controller.id
    with pytest.raises(PermissionError, match="another account"):
        claim_character(actor, str(character.id), "owner-b")
    released = release_claim(actor, "owner-a")
    assert released.claim_id == claimed.claim_id
    assert controller_snapshot(character) == before

    claim_character(actor, str(character.id), "owner-a")
    reset_claim(actor, str(character.id))
    assert not character.has_component(StudioInfluenceClaimComponent)
    assert controller_snapshot(character) == before


def test_claim_guard_blocks_direct_control_without_mutation():
    actor, character, _controller, _destination = _studio_world()
    claim_character(actor, str(character.id), "owner-a")
    before = controller_snapshot(character)

    with pytest.raises(RuntimeError, match=CLAIM_REJECTION):
        ensure_character_control_claim_allowed(actor, character)

    assert controller_snapshot(character) == before


def test_influences_are_repeatable_prompt_facts_and_core_goal_is_auditable():
    actor, character, _controller, _destination = _studio_world()
    claim_character(actor, str(character.id), "owner-a")
    soft = add_influence(
        actor,
        character,
        InfluenceRequest(category="suggestion", text="Stop for the sunset", pressure="low"),
    )
    core = add_influence(
        actor,
        character,
        InfluenceRequest(category="want", strength="core", text="Reach Copper Hollow"),
    )

    facts = influence_fragments(actor.world, character)
    assert len(facts) == 2
    assert all("Influence" in fact.text and "not a command" in fact.text for fact in facts)
    goal_text = core.get_component(StudioInfluenceComponent).goal_text
    assert goal_text in character.get_component(GoalComponent).active_goals

    remove_influence(actor, character, core.get_component(StudioInfluenceComponent).influence_id)
    assert goal_text not in character.get_component(GoalComponent).active_goals
    assert actor.world.has_entity(soft.id)


def test_core_need_change_is_bounded_and_remains_historical_after_removal():
    actor, character, _controller, _destination = _studio_world()
    claim_character(actor, str(character.id), "owner-a")
    influence = add_influence(
        actor,
        character,
        InfluenceRequest(
            category="need",
            strength="core",
            text="Eat something nourishing",
            need="hunger",
            need_delta=25,
        ),
    )
    changed_meter = character.get_component(HungerComponent).meter

    remove_influence(
        actor, character, influence.get_component(StudioInfluenceComponent).influence_id
    )

    assert character.get_component(HungerComponent).meter == changed_meter
    with pytest.raises(ValueError, match="soft-only"):
        add_influence(
            actor,
            character,
            InfluenceRequest(category="suggestion", strength="core", text="Do this"),
        )


def test_memory_uses_private_collection_and_studio_provenance():
    actor, character, _controller, _destination = _studio_world()
    claim_character(actor, str(character.id), "owner-a")

    entry = add_memory(actor, character, "The red bridge felt familiar.", ("bridge",))

    assert entry.source == "bunnyland.studio"
    assert entry.tags == ("bridge", "studio")


def test_route_and_drive_advance_only_after_an_actual_arrival():
    actor, character, controller, _destination = _studio_world()
    claim_character(actor, str(character.id), "owner-a")
    route = create_route(
        actor,
        character,
        RouteRequest(
            title="First leg",
            waypoints=(
                RouteWaypointRequest(location_id="rose"),
                RouteWaypointRequest(location_id="copper"),
            ),
        ),
    )
    result = DriveHandler().execute(
        HandlerContext(actor.world, epoch=12, actor=actor),
        _command(character, controller, "studio-van-drive", {"destination_id": "copper"}),
    )
    assert result.ok and result.plan is not None
    assert route.get_component(StudioRouteComponent).current_waypoint == 0
    assert "intended next stop is Copper Hollow" in route_fragments(actor.world, character)[0].text
    assert "Your mobile home Kitsune" in van_fragments(actor.world, character)[0].text

    execute_mutation_plan(actor.world, result.plan)

    assert route.get_component(StudioRouteComponent).current_waypoint == 1
    assert route.get_component(StudioRouteComponent).status == "completed"
    assert (
        _owned(actor, character, "segment")[0].get_component(StudioTravelSegmentComponent).kind
        == "route"
    )
    assert _owned(actor, character, "journal")[0].has_component(StudioJournalMomentComponent)


def test_drive_rejects_unknown_road_and_insufficient_fuel():
    actor, character, controller, _destination = _studio_world()
    handler = DriveHandler()
    context = HandlerContext(actor.world, epoch=1, actor=actor)

    missing = handler.execute(
        context,
        _command(character, controller, "studio-van-drive", {"destination_id": "missing"}),
    )
    assert not missing.ok and missing.reason == "no road connects those locations"

    van_entity = _owned(actor, character, "van")[0]
    van = van_entity.get_component(StudioVanComponent)
    van_entity.remove_component(StudioVanComponent)
    van_entity.add_component(replace(van, fuel_liters=1))
    empty = handler.execute(
        context,
        _command(character, controller, "studio-van-drive", {"destination_id": "copper"}),
    )
    assert not empty.ok and empty.reason == "insufficient fuel for that road distance"


def test_refuel_action_requires_a_mapped_fuel_stop():
    actor, character, controller, _destination = _studio_world()
    handler = RefuelHandler()
    context = HandlerContext(actor.world, epoch=1, actor=actor)

    rejected_result = handler.execute(
        context, _command(character, controller, "studio-van-refuel", {"liters": 10})
    )
    assert not rejected_result.ok and rejected_result.reason == "refueling requires a fuel stop"

    rose = next(
        entity
        for entity in actor.world.query().with_all([StudioLocationComponent]).execute_entities()
        if entity.get_component(StudioLocationComponent).location_id == "rose"
    )
    place = rose.get_component(StudioLocationComponent)
    rose.remove_component(StudioLocationComponent)
    rose.add_component(replace(place, kind="fuel"))
    planned_result = handler.execute(
        context, _command(character, controller, "studio-van-refuel", {"liters": 10})
    )
    assert planned_result.ok and planned_result.plan is not None

    execute_mutation_plan(actor.world, planned_result.plan)

    assert _owned(actor, character, "van")[0].get_component(StudioVanComponent).fuel_liters == 50


def test_reflection_action_creates_a_first_person_journal_entity():
    actor, character, controller, _destination = _studio_world()
    result = ReflectionHandler().execute(
        HandlerContext(actor.world, epoch=9, actor=actor),
        _command(
            character,
            controller,
            "studio-van-write-travel-reflection",
            {"text": "I followed the copper light west."},
        ),
    )
    assert result.ok and result.plan is not None

    execute_mutation_plan(actor.world, result.plan)

    moment = _owned(actor, character, "journal")[0].get_component(StudioJournalMomentComponent)
    assert moment.first_person
    assert moment.summary == "I followed the copper light west."


def test_journal_media_sync_persists_live_and_durable_results():
    actor, character, _controller, _destination = _studio_world()
    moment = record_journal(
        actor,
        character,
        kind="reflection",
        summary="I learned to listen before turning the key.",
        first_person=True,
    )
    item = moment.get_component(StudioJournalMomentComponent)
    replace_component(
        moment,
        replace(item, media_job_id="live-image", media_kind="image", media_status="queued"),
    )

    class Media(AddonMediaCapability):
        def __init__(self) -> None:
            self.jobs: dict[tuple[str, str], AddonMediaJob] = {
                ("live-image", "image"): AddonMediaJob(
                    id="live-image",
                    kind="image",
                    status="succeeded",
                    source_event_id="scene-live",
                    url="/media/live.png",
                    error=None,
                )
            }

        @property
        def image_available(self) -> bool:
            return True

        @property
        def video_available(self) -> bool:
            return True

        async def request_character_scene_image(
            self, character_id: str, *, requested_by: str, event_id: str = ""
        ) -> AddonMediaJob | None:
            del character_id, requested_by, event_id
            return None

        async def request_character_scene_video(
            self, character_id: str, *, requested_by: str, event_id: str = ""
        ) -> AddonMediaJob | None:
            del character_id, requested_by, event_id
            return None

        def get_character_scene_media_job(
            self, job_id: str, *, kind: Literal["image", "video"]
        ) -> AddonMediaJob | None:
            return self.jobs.get((job_id, kind))

        def resolve_character_scene_media_url(self, url: str) -> str:
            return f"https://play.example/api{url}" if url.startswith("/v1/") else url

    media = Media()
    _sync_journal_media(actor, character, media)
    live = _journal_resources(actor, character)[0]
    assert live.media_status == "succeeded"
    assert live.media_url == "/media/live.png"
    assert live.media_source_event_id == "scene-live"

    history = spawn_entity(
        actor.world,
        [
            WorldHistoryRecordComponent(
                summary="A durable scene",
                source_event_id="scene-durable",
                event_type="scene",
                created_at_epoch=actor.epoch,
            ),
            EventVideoComponent(
                url="/v1/public/media/videos/durable.mp4",
                source_event_id="scene-durable",
            ),
        ],
    )
    assert actor.world.has_entity(history.id)
    current = moment.get_component(StudioJournalMomentComponent)
    replace_component(
        moment,
        replace(
            current,
            media_job_id="forgotten-video",
            media_kind="video",
            media_source_event_id="scene-durable",
            media_status="running",
            media_url="",
        ),
    )

    _sync_journal_media(actor, character, media)
    durable = _journal_resources(actor, character)[0]
    assert durable.media_status == "succeeded"
    assert durable.media_url == ("https://play.example/api/v1/public/media/videos/durable.mp4")

    image_moment = record_journal(actor, character, kind="media", summary="Still frame")
    image_item = image_moment.get_component(StudioJournalMomentComponent)
    replace_component(
        image_moment,
        replace(
            image_item,
            media_job_id="forgotten-image",
            media_kind="image",
            media_source_event_id="scene-image",
            media_status="queued",
        ),
    )
    spawn_entity(
        actor.world,
        [
            WorldHistoryRecordComponent(
                summary="A durable still",
                source_event_id="scene-image",
                event_type="scene",
                created_at_epoch=actor.epoch,
            ),
            EventImageComponent(url="/media/durable.png", source_event_id="scene-image"),
        ],
    )

    _sync_journal_media(actor, character, media)

    saved_image = image_moment.get_component(StudioJournalMomentComponent)
    assert saved_image.media_status == "succeeded"
    assert saved_image.media_url == "/media/durable.png"


def test_journal_media_sync_marks_lost_jobs_retryable():
    actor, character, _controller, _destination = _studio_world()
    moment = record_journal(actor, character, kind="note", summary="A moment")
    item = moment.get_component(StudioJournalMomentComponent)
    replace_component(
        moment,
        replace(item, media_job_id="lost", media_kind="image", media_status="running"),
    )

    class MissingMedia(AddonMediaCapability):
        image_available = True
        video_available = True

        async def request_character_scene_image(
            self, character_id: str, *, requested_by: str, event_id: str = ""
        ) -> AddonMediaJob | None:
            del character_id, requested_by, event_id
            return None

        async def request_character_scene_video(
            self, character_id: str, *, requested_by: str, event_id: str = ""
        ) -> AddonMediaJob | None:
            del character_id, requested_by, event_id
            return None

        def get_character_scene_media_job(
            self, job_id: str, *, kind: Literal["image", "video"]
        ) -> AddonMediaJob | None:
            del job_id, kind
            return None

        def resolve_character_scene_media_url(self, url: str) -> str:
            return url

    _sync_journal_media(actor, character, MissingMedia())
    resource = _journal_resources(actor, character)[0]

    assert resource.media_status == "expired"
    assert "request it again" in resource.media_error
    assert _normalized_media_status("unexpected") == "failed"


def test_breakdown_opening_protection_cooldown_and_recovery():
    actor, character, _controller, _destination = _studio_world()
    van_entity = _owned(actor, character, "van")[0]
    van = van_entity.get_component(StudioVanComponent)
    van_entity.remove_component(StudioVanComponent)
    van_entity.add_component(replace(van, reliability="temperamental", completed_legs=0))

    _segment, opening_incident = drive_van(actor, character, "copper", event_seed=3)
    assert opening_incident is None

    updated = van_entity.get_component(StudioVanComponent)
    van_entity.remove_component(StudioVanComponent)
    van_entity.add_component(
        replace(
            updated,
            current_location_id="rose",
            completed_legs=2,
            breakdown_cooldown_legs=2,
        )
    )
    _segment, cooldown_incident = drive_van(actor, character, "copper", event_seed=3)
    assert cooldown_incident is None

    current = van_entity.get_component(StudioVanComponent)
    van_entity.remove_component(StudioVanComponent)
    van_entity.add_component(
        replace(
            current,
            broken_down=True,
            active_incident_id="incident",
            breakdown_cooldown_legs=BREAKDOWN_COOLDOWN_LEGS,
        )
    )
    recovered = recover_van(actor, character)
    assert not recovered.broken_down and recovered.active_incident_id == ""


@pytest.mark.asyncio
async def test_breakdown_narrative_falls_back_without_mechanical_changes(monkeypatch):
    actor, character, _controller, _destination = _studio_world()
    incident = spawn_entity(
        actor.world,
        [
            StudioBreakdownComponent(
                incident_id="incident",
                location_id="copper",
                event_seed=1,
                occurred_at_epoch=4,
            )
        ],
    )
    van = _owned(actor, character, "van")[0].get_component(StudioVanComponent)
    mechanical_before = (van.fuel_liters, van.reliability, van.broken_down)

    def unavailable(_options):
        raise RuntimeError("provider unavailable")

    monkeypatch.setattr("bunnyland_studio.mechanics.build_world_agent", unavailable)
    from bunnyland.worldgen import GenOptions

    narrative = await explain_breakdown(actor, incident, van=van, options=GenOptions())

    saved = incident.get_component(StudioBreakdownComponent)
    assert saved.narrative_source == "fallback"
    assert saved.diagnosis == narrative.diagnosis
    van_after = _owned(actor, character, "van")[0].get_component(StudioVanComponent)
    assert (
        van_after.fuel_liters,
        van_after.reliability,
        van_after.broken_down,
    ) == mechanical_before


def test_fictional_plan_is_deterministic_connected_and_fuel_feasible():
    config = FictionalGeneratorConfig(blueprint=_blueprint(), town_count=10, branch_count=3)

    first = fictional_plan("rose-seed", config)
    second = fictional_plan("rose-seed", config)

    assert first == second
    locations, roads = first
    assert len(locations) == 13
    assert len(roads) == 13
    assert roads[9].to_index == 0  # the highway loop closes
    assert {location.kind for location in locations[10:]} == {"fuel", "camp", "repair"}
    assert all(road.estimate.distance_km <= 70 for road in roads[:2])


@pytest.mark.asyncio
async def test_open_map_client_bounds_and_caches_service_calls(monkeypatch):
    calls: list[tuple[str, str]] = []

    class Response:
        def __init__(self, payload: object) -> None:
            self.payload = payload

        def raise_for_status(self) -> None:
            return None

        def json(self) -> object:
            return self.payload

    class Client:
        def __init__(self, **_options: object) -> None:
            pass

        async def __aenter__(self):
            return self

        async def __aexit__(self, *_args: object) -> None:
            return None

        async def get(self, url: str, **_options: object) -> Response:
            calls.append(("get", url))
            if "/search" in url:
                return Response(
                    [
                        {
                            "osm_type": "node",
                            "osm_id": 42,
                            "display_name": "Rose Junction",
                            "lat": "35.0",
                            "lon": "-105.0",
                        }
                    ]
                )
            return Response({"routes": [{"distance": 123400, "duration": 7200}]})

        async def post(self, url: str, **_options: object) -> Response:
            calls.append(("post", url))
            return Response(
                {
                    "elements": [
                        {
                            "type": "way",
                            "id": 9,
                            "center": {"lat": 35.1, "lon": -104.9},
                            "tags": {"amenity": "fuel", "name": "Roadrunner Fuel"},
                        }
                    ]
                }
            )

    monkeypatch.setattr("bunnyland_studio.generators.httpx.AsyncClient", Client)
    client = OpenMapClient(
        nominatim_url="https://nominatim.invalid",
        osrm_url="https://osrm.invalid",
        overpass_url="https://overpass.invalid",
        contact="operator@example.invalid",
    )
    point = GeoPoint(latitude=35, longitude=-105)

    first_search = await client.search("Rose Junction", limit=99)
    second_search = await client.search("Rose Junction", limit=99)
    first_route = await client.route(point, GeoPoint(latitude=36, longitude=-104))
    second_route = await client.route(point, GeoPoint(latitude=36, longitude=-104))
    pois = await client.pois(point, radius_meters=999_999)

    assert first_search == second_search and first_search[0].osm_id == 42
    assert first_route == second_route == RouteEstimate(123.4, 120)
    assert pois[0].tags["amenity"] == "fuel"
    assert len([call for call in calls if call[0] == "get"]) == 2
    assert calls[-1] == ("post", "https://overpass.invalid")


@pytest.mark.asyncio
async def test_real_generator_persists_osm_services_and_range_warning(monkeypatch):
    origin = LocationSelection(
        id="osm:node:1",
        name="Origin",
        point=GeoPoint(latitude=35, longitude=-105),
        osm_type="node",
        osm_id=1,
    )
    destination = LocationSelection(
        id="osm:node:2",
        name="Destination",
        point=GeoPoint(latitude=37, longitude=-103),
        osm_type="node",
        osm_id=2,
    )
    config = RealGeneratorConfig(
        blueprint=_blueprint().model_copy(update={"starting_fuel_liters": 10, "km_per_liter": 5}),
        origin=origin,
        destinations=(destination,),
        contact="operator@example.invalid",
    )
    service = OverpassPoi(
        type="way",
        id=77,
        center=OverpassCenter(lat=35.1, lon=-104.9),
        tags={"shop": "car_repair", "name": "Moss Garage"},
    )

    class Client:
        def __init__(self, **_options: object) -> None:
            pass

        async def route(self, start: GeoPoint, end: GeoPoint) -> RouteEstimate:
            return RouteEstimate(600, 500) if end == destination.point else RouteEstimate(12, 18)

        async def pois(self, _center: GeoPoint) -> tuple[OverpassPoi, ...]:
            return (service,)

    captured: dict[str, object] = {}

    async def instantiate(_actor, **options: object):
        captured.update(options)
        return "generated"

    monkeypatch.setattr("bunnyland_studio.generators.OpenMapClient", Client)
    monkeypatch.setattr("bunnyland_studio.generators._instantiate_studio", instantiate)
    from bunnyland.worldgen import GenOptions

    result = await real_generator(
        object(), "real-seed", GenOptions(generator_config=config.model_dump(mode="json"))
    )

    assert result == "generated"
    location_plans = captured["locations"]
    assert isinstance(location_plans, tuple)
    assert len(location_plans) == 3  # stable OSM identity deduplicates repeated results
    assert location_plans[2].selection.id == "osm:way:77"
    assert location_plans[2].kind == "repair"
    warnings = captured["warnings"]
    assert isinstance(warnings, tuple)
    assert "estimated van range is 50.0 km" in warnings[0]


def test_owner_scoped_http_projection_and_admin_reset():
    actor, character, controller, _destination = _studio_world()
    store = TokenStore(":memory:")
    owner_token, _owner = store.issue("owner-a", (WORLD_PLAY_SCOPE,), automatic_rotation=False)
    other_token, _other = store.issue("owner-b", (WORLD_PLAY_SCOPE,), automatic_rotation=False)
    admin_token, _admin = store.issue(
        "operator", (WORLD_PLAY_SCOPE, WORLD_ADMIN_SCOPE), automatic_rotation=False
    )
    app = create_app(actor, plugins=[plugin()], token_store=store)
    client = TestClient(app)
    owner_headers = {
        "Authorization": f"Bearer {owner_token}",
        "X-Bunnyland-Client-Id": "studio-web",
    }

    claimed = client.post(
        "/v1/play/extensions/bunnyland.studio/claims",
        headers=owner_headers,
        json={"character_id": str(character.id)},
    )
    assert claimed.status_code == 201
    assert claimed.json()["autonomous_controller_active"] is True
    assert character.get_relationships(ControlledBy)[0][1] == controller.id

    projection = client.get(
        "/v1/play/extensions/bunnyland.studio/projection", headers=owner_headers
    )
    assert projection.status_code == 200
    assert projection.json()["character_name"] == "Mira"

    empty_memories = client.get(
        "/v1/play/extensions/bunnyland.studio/memories", headers=owner_headers
    )
    assert empty_memories.status_code == 200
    assert empty_memories.json() == []
    created_memory = client.post(
        "/v1/play/extensions/bunnyland.studio/memories",
        headers=owner_headers,
        json={"text": "Inez heard the belt squeal.", "tags": ["mechanic"]},
    )
    assert created_memory.status_code == 201
    assert created_memory.json()["text"] == "Inez heard the belt squeal."
    assert created_memory.json()["tags"] == ["mechanic", "studio"]
    memories = client.get("/v1/play/extensions/bunnyland.studio/memories", headers=owner_headers)
    assert memories.status_code == 200
    assert memories.json() == [created_memory.json()]

    reflection = client.post(
        "/v1/play/extensions/bunnyland.studio/journal/reflections",
        headers=owner_headers,
        json={"text": "I will remember the sound."},
    )
    assert reflection.status_code == 201
    moment_id = reflection.json()["id"]
    pinned = client.put(
        f"/v1/play/extensions/bunnyland.studio/journal/{moment_id}/pin",
        headers=owner_headers,
    )
    assert pinned.status_code == 200
    assert pinned.json()["pinned"] is True
    unpinned = client.delete(
        f"/v1/play/extensions/bunnyland.studio/journal/{moment_id}/pin",
        headers=owner_headers,
    )
    assert unpinned.status_code == 200
    assert unpinned.json()["pinned"] is False
    assert (
        client.put(
            "/v1/play/extensions/bunnyland.studio/journal/missing/pin",
            headers=owner_headers,
        ).status_code
        == 404
    )
    assert (
        client.delete(
            "/v1/play/extensions/bunnyland.studio/journal/missing/pin",
            headers=owner_headers,
        ).status_code
        == 404
    )

    denied = client.get(
        "/v1/play/extensions/bunnyland.studio/projection",
        headers={
            "Authorization": f"Bearer {other_token}",
            "X-Bunnyland-Client-Id": "studio-web",
        },
    )
    assert denied.status_code == 403
    denied_memories = client.get(
        "/v1/play/extensions/bunnyland.studio/memories",
        headers={
            "Authorization": f"Bearer {other_token}",
            "X-Bunnyland-Client-Id": "studio-web",
        },
    )
    assert denied_memories.status_code == 403

    memory_store = actor.memory_store
    actor.memory_store = None
    unavailable_memories = client.get(
        "/v1/play/extensions/bunnyland.studio/memories", headers=owner_headers
    )
    assert unavailable_memories.status_code == 503
    actor.memory_store = memory_store

    stock_claim = client.post(
        "/v1/play/claims",
        headers={**owner_headers, "X-Bunnyland-Client-Id": "studio-web"},
        json={"character_id": str(character.id), "delivery": "header"},
    )
    assert stock_claim.status_code == 409
    assert stock_claim.json()["detail"] == CLAIM_REJECTION

    reset = client.delete(
        f"/v1/admin/extensions/bunnyland.studio/claims/{character.id}",
        headers={
            "Authorization": f"Bearer {admin_token}",
            "X-Bunnyland-Client-Id": "studio-admin",
        },
    )
    assert reset.status_code == 200
    assert not character.has_component(StudioInfluenceClaimComponent)
